# This is the configuration used to check the rubocop source code.

Rails:
  Enabled: true

AllCops:
  Exclude:
    - wor-push_notifications-aws.gemspec
    - spec/**/*
    - lib/generators/templates/add_device_token.rb

Documentation:
  Enabled: false

LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  Enabled: false
